servlet.one.url=/firstServlet.do
servlet.one.className=com.lxcecho.netty.tomcat.servlet.NettyFirstServlet

servlet.two.url=/secondServlet.do
servlet.two.className=com.lxcecho.netty.tomcat.servlet.NettySecondServlet